# Generated by Django 4.0.4 on 2022-05-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='info',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
