# Generated by Django 4.0.4 on 2022-05-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_info_age_alter_info_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='info',
            name='query',
            field=models.TextField(max_length=500),
        ),
    ]
